[package]
name = "rsyncd_exporter"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
prometheus = "0.13"
regex = "1.5"
tokio = { version = "1", features = ["full"] }
notify = "7.0.0"
warp = "0.3"
